sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t timodeus/udemy--docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timodeus/udemy--docker-react npm run test
